// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvlrsuashxiatxwtybgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2bHJzdWFzaHhpYXR4d3R5YmdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzAwMzIsImV4cCI6MjA2NTUwNjAzMn0.Lz7PR7y5dRIKDUGixUDmta_hHpgW7byok8u_m7oBHII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);